Add FormInput
SosnovichIvan/mocker pull request #16
Opened 2024-10-04 06:46 UTC by Dignot

2024-10-04 07:01 UTC, SosnovichIvan requested changes
ошибка

2024-10-04 07:01 UTC, SosnovichIvan commented on front/src/components/formItem/FormItemField/index.types.ts
> +export type FieldData = {
типы могут отличаться в зависимости от выбранного филда, плюс есть уникальные пересечения
по сути надо сделать дженерик с типом филда и дата это нативные пропсы из самой компоненты

2024-10-04 07:01 UTC, SosnovichIvan commented on front/src/components/formItem/ui/index.tsx
> +      rules={[
правила это тип общий для всех полей и задается при формирование конфига полей, не все поля обязательны

2024-10-08 07:53 UTC, SosnovichIvan requested changes
!

2024-10-08 07:53 UTC, SosnovichIvan commented on front/src/components/formItem/FormItemField/index.types.ts
> +export enum FieldType {
если вместо enum использовать Union то не придется экспортировать тип а просто передавать можно будет строкой

2024-10-08 07:53 UTC, SosnovichIvan commented on front/src/components/formItem/ui/index.tsx
> +      name={placeholder}
name={placeholder}
имя не может быть placeholder

2024-10-08 07:53 UTC, SosnovichIvan commented on front/src/components/formItem/ui/index.tsx
> +        type === FieldType.EMAIL
вся валидация приходит пропсами и в FormItemField и там реализуется вместе с инпутом

2024-10-08 07:53 UTC, SosnovichIvan commented on front/src/components/formItem/ui/index.types.ts
> +export type FieldData = {
FieldData не может быть таких свойств, все свойства идут в 1 месте в филде

2024-10-08 07:53 UTC, SosnovichIvan commented on front/src/supporting/constants/inputFieldData.ts
> +import { FieldType } from 'components/formItem/FormItemField/index.types'
FieldType импорт components/formItem должен быть таким

2024-10-08 07:53 UTC, SosnovichIvan commented on front/src/supporting/constants/inputFieldData.ts
> +export const InputFieldData = {
InputFieldData должен быть типизорован как массив филдом

2024-10-08 07:53 UTC, SosnovichIvan commented on front/src/supporting/constants/inputFieldData.ts
> +  auth: [
у каждой формы свой набор филдов а не 1 объект с разными

2024-10-09 12:59 UTC, Zela2520 commented on front/src/components/formItem/ui/index.tsx
> +    case 'text':
Для типа можно создать enum

2024-10-09 12:59 UTC, Zela2520 commented on front/src/components/formItem/ui/ui/password/ui/index.tsx
> +          required: !!isRequired,
зачем тут !!

2024-10-09 12:59 UTC, Zela2520 commented on front/src/components/formItem/ui/ui/text/ui/index.tsx
> +      key={placeholder}
Почему key = placeholder ? Мне кажется лучше name использовать. А еще лучше как-то на уровне нейминга обозначить что поле которое передаётся в FormField будет в качестве ключа использоваться. 

Я бы добавил в пропсы id: string и использовал бы в качестве ключа его, потому что id указывает на уникальность

2024-10-09 18:28 UTC, SosnovichIvan requested changes
!

2024-10-09 18:28 UTC, SosnovichIvan commented on front/src/components/formItem/ui/index.types.ts
> +  id: 'string'
'string' почему в ковычках? это теперь не тип строка а юнион со значением 'string'

2024-10-09 18:28 UTC, SosnovichIvan commented on front/src/components/formItem/ui/index.types.ts
> +type TextField = FieldData<'text' | 'email', TextProps>
email смысл создавать тип email если он такой же как текст? оставь один

2024-10-09 18:28 UTC, SosnovichIvan commented on front/src/components/formItem/ui/ui/password/ui/index.tsx
> +      key={placeholder}
placeholder не обязательное поле! плюс ключ тут не нужен так тут нет маппинга и тогда лучше уж сделать name

2024-10-09 18:28 UTC, SosnovichIvan commented on front/src/components/formItem/ui/ui/password/ui/index.tsx
> +          message: `Пожалуйста, введите  ${placeholder}!`,
message должен приходит в пропсе так как текстовка может отличаться
по сути все правила должны придти массивом в общих типах всех филдов
так как описания правил для всех одинаковые

2024-10-09 18:28 UTC, SosnovichIvan commented on front/src/components/formItem/ui/ui/password/ui/index.tsx
> +      <InputPassword placeholder={placeholder} />
<InputPassword placeholder={placeholder} /> = <InputPassword {... { placeholder} } />

2024-10-09 18:28 UTC, SosnovichIvan commented on front/src/components/formItem/ui/ui/text/ui/index.tsx
> +    <Form.Item
замечания все те же что и в пароле
плюс вопрос почему тут ключ id а там нет?
и не нужен и id и name хватит одного свойства имени поля

2024-10-09 18:29 UTC, SosnovichIvan commented on front/src/components/formItem/ui/index.tsx
> +    case 'text':
лучше так, а то енам везде пойдет на экпорт и импорт
тут тс сам покажет чего не хватает

2024-10-10 16:54 UTC, SosnovichIvan requested changes
!

2024-10-10 16:54 UTC, SosnovichIvan commented on front/src/components/formItem/ui/index.types.ts
> +type ErrorMessage =
ErrorMessage зачем? Сообщения передаются в формате строки

2024-10-10 16:54 UTC, SosnovichIvan commented on front/src/components/formItem/ui/index.types.ts
> +  rule?: {
тип правил берется с ант дизайна

2024-10-10 16:54 UTC, SosnovichIvan commented on front/src/components/formItem/ui/index.types.ts
типы идут сверху вниз
от главного и ниже

2024-10-10 16:54 UTC, SosnovichIvan commented on front/src/components/formItem/ui/ui/password/ui/index.tsx
> +    <Form.Item name={name} rules={rule}>
rule почему не назвать rules и не сделать просто
{...{ name, rules }}

2024-10-10 16:54 UTC, SosnovichIvan commented on front/src/components/formItem/ui/ui/text/ui/index.tsx
> +    <Form.Item name={name} rules={rule}>
тот же вопрос

2024-10-15 16:11 UTC, SosnovichIvan requested changes
!

2024-10-15 16:11 UTC, SosnovichIvan commented on front/src/supporting/constants/FormData.ts
front/src/supporting/constants/FormData.ts это не должно лежать в папке supporting
должно быть по месту использования
то есть, или страница или виджет (лучше виджет) авторизации и в нем лежит конфиг для полей авторизации

2024-10-16 22:31 UTC, Zela2520 commented on front/src/components/formItem/ui/ui/text/ui/index.tsx
> +      key={placeholder}
имя да, но не placeholder

2024-10-18 06:51 UTC, SosnovichIvan requested changes
!

2024-10-18 06:51 UTC, SosnovichIvan commented on front/src/widgets/authForm/ui/authFormData.ts
> +    field: [
field скорее всего fields

2024-10-18 06:51 UTC, SosnovichIvan commented on front/src/widgets/authForm/ui/authFormData.ts
файл конфига идет по структуре
widgets/authForm/config/formFileds.ts

2024-10-23 07:34 UTC, SosnovichIvan requested changes
!

2024-10-23 07:34 UTC, SosnovichIvan commented on front/src/widgets/authForm/config/formFileds.ts
> +export const FormFileds: { fields: FormField[] }[] = [
зачем делать объект если там только массив полей? почему не сделать просто массив?
export const FormFileds: FormField[] = []

2024-10-23 10:45 UTC, Zela2520 commented on front/src/widgets/authForm/ui/index.tsx
> +    <section>
section тоже лучше вынести в отдельный dummy component
сделать reset стилей по умолчанию, задать дефолтные стили и пропсами отыгрывать может flow, display

2024-11-03 14:05 UTC, SosnovichIvan approved these changes

2024-11-03 14:05 UTC, SosnovichIvan commented on front/src/components/formItem/ui/fields/password/ui/index.tsx
> +      <InputPassword {...{ placeholder }} />
не

2024-11-03 14:05 UTC, merged